# PostgreSQL + pgvector for Hodor
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hodor-postgres-pvc
  namespace: hodor
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: hodor
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30032
      name: postgres
  selector:
    app: hodor-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hodor-postgres
  namespace: hodor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hodor-postgres
  template:
    metadata:
      labels:
        app: hodor-postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: hodor
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command: [pg_isready, -U, postgres, -d, hodor]
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command: [pg_isready, -U, postgres, -d, hodor]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hodor-postgres-pvc
