namespace Papel.Integration.Domain.Enums;

public enum TXN_TYPE
{
    TopupByBankAccount = 100,
    TopupByAtm,
    TopupByCard,
    TopupByStoredCard,
    TopupByCashback,
    PrepaidTopupByCashPayment = 105,
    TopUpByNoReferenceRefund = 106,
    TopupBonusMoney = 107,
    PaymentOfReferralFactoryQualifyReferrerReward,
    PaymentOfReferralFactoryQualifyInvitedReward,
    MerchantCoveredCashback,
    TopupByMerchant,

    TransferToBankAccount = 200,
    TransferToAtm,
    TransferToAccount,
    TransferByAraf,
    TransferByAskForMoney,
    TransferBySplitTheBill,
    TransferByBetweenAccounts,
    TransferByRemittance,
    TransferToAnotherPersonBankAccount,
    TransferByRemittanceInbound,
    TransferByPWP = 221,
    TransferByCorporate = 222,

    InvoicePaymentByAccount = 300,
    InvoicePaymentByStoredCard,

    ExpenseAccountOpening = 400,
    ExpenseAccountMonthlyUsage,
    ExpenseVirtualCardOpening,
    ExpenseVirtualCardMonthlyUsage,
    PrepaidBalanceInquiry = 404,
    ExpensePhysicalCardOpening,
    ExpensePhysicalCardMonthlyUsage,

    PaymentViaWallet = 500,
    PaymentViaWalletByCard,
    PaymentViaWalletByStoredCard,
    PaymentViaWalletByAccount,
    PaymentViaWalletByExtraLimit,
    PaymentPos,
    PaymentEcom,
    TFSPaymentPos,
    TFSPaymentEcom,
    PrePayNationPayment,
    PerDigitalPayment,

    PanelIncrease = 600,
    PanelDecrease,
    PrepaidAdjustmentDebit,
    PrepaidAdjustmentCredit,
    CreateTxnForPf,
    CancelTxnForPf,

    RefundOfTransferToAtm = 700,
    RefundOfTransferByAraf,
    RefundOfTopup,
    RefundOfExpenseAccountOpening,
    RefundOfExpenseAccountMonthlyUsage,
    RefundOfExpenseVirtualCardOpening,
    RefundOfExpenseVirtualCardMonthlyUsage,
    RefundOfTopupByBankAccount,
    RefundOfTopupByAtm,
    RefundOfTopupByCard,
    RefundOfTopupByStoredCard,
    RefundOfCashback,
    RefundOfPaymentPos,
    RefundOfPaymentEcom,

    RefundOfPrepaidBalanceInquiry,

    RefundOfTransferToBankAccount,
    RefundOfPrepaidAdjustmentDebit,
    RefundOfPrepaidAdjustmentCredit,
    RefundOfTopUpByNoReferenceRefund,
    RefundOfPrepaidTopupByCashPayment,
    RefundOfTFSPaymentPos,
    RefundOfTFSPaymentEcom,
    RefundExpensePhysicalCardOpening,
    RefundExpensePhysicalCardMonthlyUsage,
    RefundOfRemittance,
    RefundOfPWP,
    RefundOfMerchantCoveredCashback,

    UndefinedOperation = 999
}
