global using System.Globalization;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using FluentAssertions;
global using Microsoft.AspNetCore.Hosting;
global using Xunit;
global using Papel.Integration.Common.Tests;
global using RestSharp;
